version: '3'
services:
  orientdb:
    image: orientdb:2.2.33
    ports:
      - "2424:2424"
      - "2480:2480"
    volumes:
      - ${PWD}/data/backup:/orientdb/backup
      - ${PWD}/data/databases:/orientdb/databases
    user: "${UID}:${GID}"
    environment:
      ORIENTDB_ROOT_PASSWORD: root
